version: '3.8'

services:
  petdb:
    container_name: pet_db
    image: mysql:latest
    platform: linux/amd64
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_PASSWORD: pet
      MYSQL_ROOT_PASSWORD: pet
    networks:
      - petclinic_network

  petclinic:
    image: jendaredocker/jendarey-petclinic:v1
    container_name: jendarey-petclinic
    restart: always
    ports:
      - "15000:8080"
    depends_on:
      - petdb
    environment:
      MYSQL_HOST:  pet_db
      MYSQL_DB_NAME: pet
      MYSQL_USER: root
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: pet
    networks:
      - petclinic_network

  adminer:
    image: adminer
    platform: linux/amd64
    restart: always
    ports:
      - 18080:8080

networks:
  petclinic_network:
    driver: bridge



