version: '3.8'

services:
  petdb:
    image: mysql:latest
    platform: linux/amd64
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: user
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - petclinic_network

  petclinic:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - petdb
    environment:
      MYSQL_HOST:  pet-clinic-master-petdb-1
      MYSQL_DB_NAME: user
      MYSQL_USER: root
      MYSQL_PORT: 3306
      MYSQL_PASSWORD: 123456

    networks:
      - petclinic_network

  adminer:
    image: adminer
    platform: linux/amd64
    restart: always
    ports:
      - 18080:8080

networks:
  petclinic_network:
    driver: bridge



